name = input('What is your name? ')
print('Welcome to Compound Interest Calculator ' + name)
principal = input('What is the principal? ')
rate = input('What is the rate? ')
time = input('What is the time? ')
number = input('What is the amount of time you have applied this interest? ')
ratio = (int(rate)/int(number))
power = (int(number) * int(time))
express = (1 + int(ratio)) 
Amount = (int(principal) * (int(express))**int(power))
Compound_Interest = (int(Amount) - int(principal))
print(Amount)
print(Compound_Interest)
print('This is your Compound Interest ' + name)
print('Thank you for using this product created by Nneji Kamsi...')
 